//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireGnome.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HireGnome.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //.Index(t =&gt; t.Description, unique: true);
        ///
        ///           //Sql(HireGnome.Properties.Resources.MyScript1);
        ///            Sql(&quot;INSERT INTO Roles (Rol, Description) VALUES (&apos;admin&apos;, &apos;Admin rol&apos;)&quot;);
        ///            Sql(&quot;INSERT INTO Roles (Rol, Description) VALUES (&apos;user&apos;, &apos;User rol&apos;)&quot;);
        ///            Sql(&quot;INSERT INTO Users (Email, Password, Name, Country, RolId) VALUES (&apos;admin@admin.com&apos;, &apos;G4/XovvSDFEMYXVtyp3q0+Hfq4pEzy7m3pcoUvno7Bc=&apos;, &apos;admin&apos;, &apos;Spain&apos;, 1)&quot;);
        ///            Sql(&quot;INSERT INTO Products (Name, Details, P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string initial_data {
            get {
                return ResourceManager.GetString("initial_data", resourceCulture);
            }
        }
    }
}
